### PR TITLE
Unrbreak things

### PR DESCRIPTION
**Pull request by benbalter**
This pull request should get things working locally. ~~It will definitely need updated tests,~~ but a few things to note ~~so far~~:

* Don't pass the tokens to the cloner, let the cloner grab them from the environment
* Endpoint is now `/sync`, optionally with `?squash` argument
* Don't pass `is_public` to the cloner, use ~~the API~~ `squash` to figure that out
* Don't pass the tmpdir to the cloner, make it when we init the cloner instance
* Fix: Use destination repo as origin, and upstream as the branch, each with different clone urls/tokens

### CODE REVIEW

**Comment by gjtorikian** [comment]
> Don't pass is_public to the cloner, use the API to figure that out

I might advise against this. The nomenclature of `public` or `private` is what probably should change, not the bool that's passed. Something like `update_with_squash` and just `update`. It shouldn't matter whether the destination is public or private.

An alternative is to just do `/update&squash...`. If `!params[:squash].nil?`, do it, otherwise, don't.

**Comment by benbalter** [comment]
You're 100% right. I'm going to undo that. It was one of those "keep changing things until it works" strategies.

**Comment by gjtorikian** [comment]
@benbalter Lemme grab that in this PR then. I'd hate for you to clean up my mistakes. :grin:

**Comment by benbalter** [comment]
Okay. Sorry for the hassle. Complicating things, I didn't see your changes on the branch and made some ugly merge conflicts, but think it should be all resolved now.

Works locally. See https://github.com/benbaltertest/downstream/pull/5. Output looks like this:

```
09:54:04 web.1    | 127.0.0.1 - - [27/Jan/2015 09:54:04] "POST /sync?dest_repo=benbaltertest%2Fdownstream&squash= HTTP/1.1" 200 - 0.0385
09:54:08 worker.1 | I, [2015-01-27T09:54:08.125341 #86445]  INFO -- : Cloning benbaltertest/downstream from github.com...
09:54:09 worker.1 | I, [2015-01-27T09:54:09.164141 #86445]  INFO -- : New Cloner instance initialized
09:54:09 worker.1 | I, [2015-01-27T09:54:09.164446 #86445]  INFO -- :   * tmpdir: /var/folders/_b/0_w51d1147dflr6ff5ldkn2c0000gn/T/repository-sync/repos/142237042840120150127-86332-w4n9ow
09:54:09 worker.1 | I, [2015-01-27T09:54:09.164608 #86445]  INFO -- :   * after_sha: 87d43edc091d459e8c4bd0e5cc51bd75934c56df
09:54:09 worker.1 | I, [2015-01-27T09:54:09.164990 #86445]  INFO -- :   * squash:
09:54:09 worker.1 | I, [2015-01-27T09:54:09.165358 #86445]  INFO -- :   * destination_hostname: github.com
09:54:09 worker.1 | I, [2015-01-27T09:54:09.165515 #86445]  INFO -- :   * destination_repo: benbaltertest/downstream
09:54:09 worker.1 | I, [2015-01-27T09:54:09.165662 #86445]  INFO -- :   * originating_hostname: github.com
09:54:09 worker.1 | I, [2015-01-27T09:54:09.165797 #86445]  INFO -- :   * originating_repo: benbaltertest/upstream
09:54:09 worker.1 | I, [2015-01-27T09:54:09.165958 #86445]  INFO -- :   * git: #<Git::Base:0x007fa80b8f9958>
09:54:09 worker.1 | I, [2015-01-27T09:54:09.169616 #86445]  INFO -- : Adding remote for benbaltertest/upstream on github.com...
09:54:09 worker.1 | I, [2015-01-27T09:54:09.189475 #86445]  INFO -- : Fetching benbaltertest/upstream...
09:54:10 worker.1 | I, [2015-01-27T09:54:10.442643 #86445]  INFO -- : Checking out update-1422370450
09:54:10 worker.1 | I, [2015-01-27T09:54:10.466245 #86445]  INFO -- : Merging benbaltertest/upstream/master into update-1422370450...
09:54:10 worker.1 | I, [2015-01-27T09:54:10.466485 #86445]  INFO -- : Squashing!
09:54:10 worker.1 | I, [2015-01-27T09:54:10.466654 #86445]  INFO -- : Running command git merge --squash otherrepo-1422370449/master
09:54:10 worker.1 | I, [2015-01-27T09:54:10.477916 #86445]  INFO -- : Result: Automatic merge went well; stopped before committing as requested
09:54:10 worker.1 | Auto-merging foo.md
09:54:10 worker.1 | Squash commit -- not updating HEAD
09:54:10 worker.1 |
09:54:10 worker.1 | I, [2015-01-27T09:54:10.493345 #86445]  INFO -- : Pushing to origin...
09:54:10 worker.1 | I, [2015-01-27T09:54:10.493649 #86445]  INFO -- : Running command git push origin update-1422370450
09:54:12 worker.1 | I, [2015-01-27T09:54:12.006211 #86445]  INFO -- : Result: To https://<TOKEN>-oauth-basic@github.com/benbaltertest/downstream.git
09:54:12 worker.1 |  * [new branch]      update-1422370450 -> update-1422370450
09:54:12 worker.1 |
09:54:12 worker.1 | I, [2015-01-27T09:54:12.466831 #86445]  INFO -- : Pull request #5 created.
09:54:14 worker.1 | I, [2015-01-27T09:54:14.700308 #86445]  INFO -- : Merged PR #5
09:54:14 worker.1 | I, [2015-01-27T09:54:14.700647 #86445]  INFO -- : Deleting benbaltertest/downstream/update-1422370450
09:54:14 worker.1 | I, [2015-01-27T09:54:14.824974 #86445]  INFO -- : fin
09:54:14 worker.1 | I, [2015-01-27T09:54:14.847340 #86445]  INFO -- : Cleaning up /var/folders/_b/0_w51d1147dflr6ff5ldkn2c0000gn/T/repository-sync/repos/142237042840120150127-86332-w4n9ow
```

Just have to get tests working on Travis and this should be good to go.

**Comment by benbalter** [comment]
@gjtorikian took much longer than I'd like to admit, but finally got things working, locally, when testing locally, and in travis (travis's tmpdir is strange apparently). Ready for your :eyes: when you are.

**Comment by gjtorikian** [comment]
This looks great to me. I made a few changes inline; in particular, the `squash` code wasn't accurate. But everything else is :sparkles:.

If you're happy with it, feel free to merge and deploy.

**Comment by benbalter** [comment]
:heart: the attention to detail in all of your changes. Will merge/deploy tomorrow when I'm on solid wifi.

**Pull request merged**
