### PR TITLE
Create Cloner instance when performing the clone

### PR DESCRIPTION
**Pull request by benbalter**
Working through https://github.com/gjtorikian/repository-sync/pull/13, I noticed the cloner job was a bit odd in that it felt like it should be an instance, but was using a handful of class variables, pass around common arguments to each method.

This pull request creates a `Cloner` class, which the job creates with an options hash, and then calls `Cloner#clone`. The philosophy behind the Cloner class was to break things up into tiny, reusable methods so that the logic was less frail and so that things are easier to test.

A few other things to note:

* Behavior should (hopefully) be identical
* Whenever possible, passing around a hash of options (with defaults) rather than a long string of arguments
* Uses Ruby's native Logger (which you can specify the log level of) rather than `puts`
* Use a common `run_command` method, via `Open3`, which should be natively blocking
* Use webmock to stub entire HTTP responses via Octokit
* Created two entire git dirs (upstream, downstream) as fixtures. Downstream has one commit and one file, upstream has three commits and two files (to test squashing)
* Use `tmp` as a scratch dir, rather than the fixture dir

### CODE REVIEW

**Comment by gjtorikian** [comment]
I'm guessing this'll need similar .travis.yml changes as in jekyll-auth: https://github.com/benbalter/jekyll-auth/blob/dcae4205f18ed94b3653503a61c65cc3e1ded3a6/.travis.yml#L4-L6

Other than that, looks absolutely great.

**Comment by benbalter** [comment]
Fixed via 3c47c1e. Just needed to set the env vars. It'll set the user on init if specified.

**Comment by gjtorikian** [comment]
@benbalter I just gave you collab/commit rights, go :pig2: wild.

**Comment by benbalter** [comment]
hold on to your butts

**Pull request merged**
